<?php

return [

    'AD'    => 'Arizona Diamondbacks',
    'AB'    => 'Atlanta Braves',
    'BO'    => 'Baltimore Orioles',
    'BRS'   => 'Boston Red Sox',
    'CC'    => 'Chicago Cubs',
    'CWS'   => 'Chicago White Sox',
    'CR'    => 'Cincinnati Reds',
    'CI'    => 'Cleveland Indians',
    'CLR'   => 'Colorado Rockies',
    'DT'    => 'Detroit Tigers',
    'HA'    => 'Houston Astros',
    'KCR'   => 'Kansas City Royals',
    'LAA'   => 'Los Angeles Angels',
    'LAD'   => 'LA Dodgers',
    'MM'    => 'Miami Marlins',
    'MB'    => 'Milwaukee Brewers',
    'MT'    => 'Minnesota Twins',
    'NYM'   => 'New York Mets',
    'NYY'   => 'New York Yankees',
    'OA'    => 'Oakland Athletics',
    'PP'    => 'Philadelphia Phillies',
    'PBP'   => 'Pittsburgh Pirates',
    'SDP'   => 'San Diego Padres',
    'SFG'   => 'San Francisco Giants',
    'SM'    => 'Seattle Mariners',
    'SLC'   => 'St Louis Cardinals',
    'TBR'   => 'Tampa Bay Rays',
    'TR'    => 'Texas Rangers',
    'TBJ'   => 'Toronto Blue Jays',
    'WN'    => 'Washington Nationals',

];