<?php

return [

    'ARI'   => 'Arizona Diamondbacks',
    'ATL'   => 'Atlanta Braves',
    'BAL'   => 'Baltimore Orioles',
    'BOS'   => 'Boston Red Sox',
    'CHC'   => 'Chicago Cubs',
    'CWS'   => 'Chicago White Sox',
    'CIN'   => 'Cincinnati Reds',
    'CLE'   => 'Cleveland Indians',
    'COL'   => 'Colorado Rockies',
    'DET'   => 'Detroit Tigers',
    'HOU'   => 'Houston Astros',
    'KAN'   => 'Kansas City Royals',
    'LAD'   => 'Los Angeles Dodgers',
    'LAA'   => 'Los Angeles Angels',
    'MIA'   => 'Miami Marlins',
    'MIL'   => 'Milwaukee Brewers',
    'MIN'   => 'Minnesota Twins',
    'NYM'   => 'New York Mets',
    'NYY'   => 'New York Yankees',
    'OAK'   => 'Oakland Athletics',
    'PHI'   => 'Philadelphia Phillies',
    'PIT'   => 'Pittsburgh Pirates',
    'SDP'   => 'San Diego Padres',
    'SFG'   => 'San Francisco Giants',
    'SEA'   => 'Seattle Mariners',
    'STL'   => 'St. Louis Cardinals',
    'TAM'   => 'Tampa Bay Rays',
    'TEX'   => 'Texas Rangers',
    'TOR'   => 'Toronto Blue Jays',
    'WSH'   => 'Washington Nationals',

];